services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: buenos_cakes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
